document.querySelector(".header").style.backgroundColor = "#ff4500";
document.querySelector(".header").style.color  = "white";
document.querySelector(".header").style.padding = "2rem";
document.querySelector(".header").style.textAlign = "center";
document.getElementById("title").textContent = "Javascript Dom Assignment";
document.querySelector(".nav-item").style.listStyle = "none";
document.querySelector(".nav-item").style.display = "flex"
document.querySelector(".nav-item").style.justifyContent = "center"
document.querySelector(".nav-item").style.gap = "2rem"
document.querySelector("#username").value = "Anthony"
document.querySelector("#password").value = "123456"
document.querySelector("#password").type = "text";
document.querySelector("#password").disabled = "true"
document.querySelector("#username").disabled = "true"
document.querySelector(".btn").style.backgroundColor ="#C0EFC0"
document.querySelector(".btn").style.padding ="0.5rem"
document.querySelector(".btn").style.borderRadius ="0.5rem"
document.querySelector(".btn").style.borderStyle ="none"
document.querySelector(".btn").style.borderStyle ="none"
document.querySelector(".btn").textContent ="Giriş Yap"
document.querySelector(".btn").style.cursor ="pointer"
document.getElementById("projects").firstChild.textContent = "Js Dom Projects"